[workspace]

[package]
name = "p3-04-02-migrations-solution"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "postgres", "macros", "migrate", "chrono", "uuid"] }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
serial_test = "3"
