//! A minimal gRPC "notes" service over `tonic` — see `README.md` for the
//! theory and how `proto/notes.proto` gets compiled into the `notes`
//! module below (via `build.rs`).
//!
//! Tests in this lesson call the service's methods directly (constructing
//! a `tonic::Request` and awaiting the async method), the same way you'd
//! unit test any other struct — no real network connection or a running
//! server is needed to exercise the RPC handler logic. A real
//! service-to-service call would go over HTTP/2 via `tonic::transport`
//! (see `main.rs`-style examples in the `tonic` docs), but that's
//! orthogonal to the request-handling logic under test here.

use std::collections::HashMap;
use std::sync::Mutex;
use tonic::{Request, Response, Status};

/// Generated by `build.rs` from `proto/notes.proto`: `Note`,
/// `CreateNoteRequest`, `GetNoteRequest`, `ListNotesRequest`,
/// `ListNotesResponse`, plus the `notes_service_server` module containing
/// the `NotesService` trait and `NotesServiceServer` wrapper you'd hand to
/// `tonic::transport::Server` in a real `main.rs`.
pub mod notes {
    tonic::include_proto!("notes");
}

use notes::{CreateNoteRequest, GetNoteRequest, ListNotesRequest, ListNotesResponse, Note};

/// The service implementation. Notes are stored in memory, keyed by a
/// monotonically increasing id (stringified) — a real system would use a
/// database here (e.g. the sqlx patterns from Phase 3 or the toy queue's
/// `PostgresQueue`), but the point of this lesson is the gRPC request/
/// response/error-handling shape, not storage.
#[derive(Default)]
pub struct NotesServiceImpl {
    state: Mutex<NotesState>,
}

#[derive(Default)]
struct NotesState {
    next_id: u64,
    notes: HashMap<String, Note>,
}

impl NotesServiceImpl {
    pub fn new() -> Self {
        Self::default()
    }
}

#[tonic::async_trait]
impl notes::notes_service_server::NotesService for NotesServiceImpl {
    /// Creates a note, assigns it an id, stores it, and returns the stored
    /// `Note` (including its new id) wrapped in `Response`.
    async fn create_note(
        &self,
        request: Request<CreateNoteRequest>,
    ) -> Result<Response<Note>, Status> {
        todo!(
            "let req = request.into_inner(); lock self.state; id = state.next_id.to_string(), \
             state.next_id += 1; build note = Note {{ id: id.clone(), title: req.title, body: req.body }}; \
             state.notes.insert(id, note.clone()); return Ok(Response::new(note))"
        )
    }

    /// Looks the note up by id. Returns `Status::not_found` (not a panic,
    /// not an `Ok` with an empty `Note`) when the id doesn't exist — gRPC
    /// errors are values, exactly like axum's `Result<T, ApiError>` from
    /// Phase 3, just carried by `tonic::Status` instead of an HTTP status
    /// code + JSON body.
    async fn get_note(&self, request: Request<GetNoteRequest>) -> Result<Response<Note>, Status> {
        todo!(
            "let req = request.into_inner(); lock self.state; match state.notes.get(&req.id) {{ \
             Some(note) => Ok(Response::new(note.clone())), \
             None => Err(Status::not_found(format!(\"note {{}} not found\", req.id))) }}"
        )
    }

    /// Returns every stored note. Order is unspecified (a `HashMap` has no
    /// stable iteration order) — real pagination/ordering is out of scope
    /// for this toy lesson.
    async fn list_notes(
        &self,
        _request: Request<ListNotesRequest>,
    ) -> Result<Response<ListNotesResponse>, Status> {
        todo!(
            "lock self.state; let notes: Vec<Note> = state.notes.values().cloned().collect(); \
             return Ok(Response::new(ListNotesResponse {{ notes }}))"
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use notes::notes_service_server::NotesService;

    #[tokio::test]
    async fn creates_and_fetches_a_note() {
        let service = NotesServiceImpl::new();

        let created = service
            .create_note(Request::new(CreateNoteRequest {
                title: "Rust notes".to_string(),
                body: "traits are structural, not nominal".to_string(),
            }))
            .await
            .unwrap()
            .into_inner();

        assert!(!created.id.is_empty());
        assert_eq!(created.title, "Rust notes");

        let fetched = service
            .get_note(Request::new(GetNoteRequest {
                id: created.id.clone(),
            }))
            .await
            .unwrap()
            .into_inner();

        assert_eq!(fetched, created);
    }

    #[tokio::test]
    async fn get_note_returns_not_found_status_for_a_missing_id() {
        let service = NotesServiceImpl::new();

        let err = service
            .get_note(Request::new(GetNoteRequest {
                id: "does-not-exist".to_string(),
            }))
            .await
            .unwrap_err();

        assert_eq!(err.code(), tonic::Code::NotFound);
    }

    #[tokio::test]
    async fn list_notes_returns_every_created_note() {
        let service = NotesServiceImpl::new();

        service
            .create_note(Request::new(CreateNoteRequest {
                title: "first".to_string(),
                body: "".to_string(),
            }))
            .await
            .unwrap();
        service
            .create_note(Request::new(CreateNoteRequest {
                title: "second".to_string(),
                body: "".to_string(),
            }))
            .await
            .unwrap();

        let listed = service
            .list_notes(Request::new(ListNotesRequest {}))
            .await
            .unwrap()
            .into_inner();

        assert_eq!(listed.notes.len(), 2);
        let mut titles: Vec<&str> = listed.notes.iter().map(|n| n.title.as_str()).collect();
        titles.sort_unstable();
        assert_eq!(titles, vec!["first", "second"]);
    }

    #[tokio::test]
    async fn each_created_note_gets_a_distinct_id() {
        let service = NotesServiceImpl::new();

        let first = service
            .create_note(Request::new(CreateNoteRequest {
                title: "a".to_string(),
                body: "".to_string(),
            }))
            .await
            .unwrap()
            .into_inner();
        let second = service
            .create_note(Request::new(CreateNoteRequest {
                title: "b".to_string(),
                body: "".to_string(),
            }))
            .await
            .unwrap()
            .into_inner();

        assert_ne!(first.id, second.id);
    }
}
