//! The exact same error type as `01-hand-written-error.rs` — same variants,
//! same messages, same source chain — but `Display`, `Error`, and
//! `From<std::io::Error>` are generated by `#[derive(thiserror::Error)]`
//! instead of typed out by hand. Run both and diff the output: it's
//! identical.

#[derive(Debug, thiserror::Error)]
pub enum RatingsError {
    #[error("could not read ratings file: {0}")]
    Io(#[from] std::io::Error),

    #[error("line {line}: missing score")]
    MissingScore { line: usize },

    #[error("line {line}: invalid score: {source}")]
    InvalidScore {
        line: usize,
        #[source]
        source: std::num::ParseIntError,
    },
}

fn print_with_source(err: &RatingsError) {
    println!("{err}");
    if let Some(source) = std::error::Error::source(err) {
        println!("  caused by: {source}");
    }
}

fn main() {
    print_with_source(&RatingsError::MissingScore { line: 2 });

    let source = "oops".parse::<u8>().unwrap_err();
    print_with_source(&RatingsError::InvalidScore { line: 5, source });

    let io_source = std::fs::read_to_string("no-such-ratings-file.txt").unwrap_err();
    print_with_source(&RatingsError::Io(io_source));
}
